import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/layouts/Header";
import Footer from "@/layouts/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen h-full flex flex-col ${inter.className}
`}
      >
        {/* @ts-expect-error Async Server Component */}
        <Header /> {children}
        <Footer />
      </body>
    </html>
  );
}
